### PR TITLE
fix(Angular InstantSearch): use <link> for satellite styles

### PR DESCRIPTION
**Pull request by tkrugg**
This fixes the compatibility issue with CodeSandbox, of examples running Angular 12.
Examples running Angular 6 still work, and [most have a PR open to update them to 12](https://github.com/algolia/doc-code-samples/issues/255).
I'll be updating other currently open PRs separately: https://github.com/algolia/doc-code-samples/pull/261 and https://github.com/algolia/doc-code-samples/pull/254.

Examples updated in this PR:

[Angular InstantSearch/algolia-insights in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/algolia-insights)
[Angular InstantSearch/algolia-insights in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/algolia-insights)

[Angular InstantSearch/autocomplete-results-page in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/autocomplete-results-page)
[Angular InstantSearch/autocomplete-results-page in stackbliz](https://stackbliz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/autocomplete-results-page)

[Angular InstantSearch/getting-started in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/getting-started)
[Angular InstantSearch/getting-started in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/getting-started)

[Angular InstantSearch/infinite-scroll in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/infinite-scroll)  ❌ (this one doesn't work, it's a codesandbox typescript issue https://github.com/codesandbox/codesandbox-client/issues/2634)
[Angular InstantSearch/infinite-scroll in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/infinite-scroll)

[Angular InstantSearch/multi-index-autocomplete in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/multi-index-autocomplete)
[Angular InstantSearch/multi-index-autocomplete in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/multi-index-autocomplete)

[Angular InstantSearch/multi-index-hits in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/multi-index-hits)
[Angular InstantSearch/multi-index-hits in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/multi-index-hits)

[Angular InstantSearch/refresh in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/refresh)
[Angular InstantSearch/refresh in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/refresh)

[Angular InstantSearch/routing-basic in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/routing-basic)
[Angular InstantSearch/routing-basic in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/routing-basic)

[Angular InstantSearch/routing-seo-friendly in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/routing-seo-friendly)
[Angular InstantSearch/routing-seo-friendly in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/routing-seo-friendly)  ❌ (this one doesn't work, it's a codesandbox typescript issue https://github.com/codesandbox/codesandbox-client/issues/2634)

[Angular InstantSearch/routing-state-mapping in codesandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular+InstantSearch/routing-state-mapping)
[Angular InstantSearch/routing-state-mapping in stackblitz](https://stackblitz.com/github/algolia/doc-code-samples/tree/codesandbox-compat/Angular%20InstantSearch/routing-state-mapping) 

NB: some of the examples still don't work due to a codesandbox issue. We should just use stackblitz for all Angular examples.

### CODE REVIEW

**Review by francoischalifour — APPROVED** [review]
We could include a CSS reset to avoid default browser styling.

**Comment by dhayab** [comment]
> We could include a CSS reset to avoid default browser styling.

The satellite.css file includes a reset for all DOM elements related to InstantSearch, and there's actually a reset for `body` in create-instantsearch-app (in master, not released): https://github.com/algolia/create-instantsearch-app/blob/master/src/templates/Angular%20InstantSearch/src/styles.css.

I'll do a PR to add them after this one is merged, what do you think?

**Comment by francoischalifour** [comment]
@dhayab This branch doesn't include the changes from `master` then? Browser styles are not reset [on the preview](https://qgnivxgkw.github.stackblitz.io/).

**Comment by dhayab** [comment]
Sorry I didn't explain it well. The reset styles are in the CLI repository, and could be reused here. The samples in this (doc-code-samples) repository do not contain those reset CSS rules.

**Comment by francoischalifour** [comment]
Right, sorry I didn't see the CISA mention. That's fine to me if we add reset styles later 🙂

**Review by dhayab — APPROVED** [review]

**Pull request merged**
